---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    app_name: devopsacademy
    app_user: ubuntu
    app_dir: /home/{{ app_user }}/{{ app_name }}
    domain_name: devopsacademy.cloud-stacks.com
    git_repo: https://github.com/Maged2344/DevopsAcademy.git
    git_branch: main

  children:
    webservers:
      hosts:
        production:
          ansible_host: "{{ lookup('env', 'SERVER_IP') | default('20.25.62.124', true) }}"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('~/.ssh/id_rsa', true) }}"

    staging:
      hosts:
        # staging-server:
        #   ansible_host: x.x.x.x
        #   ansible_user: ubuntu
